version: "3.9"
services:
  dev:
    build: 
      dockerfile: ./Dockerfile.dev
    ports:
      - "8020:8020"
    command:
    - go
    - run
    - cmd/main.go
    environment:
      WK_PORT: 8020
      WK_PG_HOST: db
      WK_PG_PORT: 5432
      WK_PG_USER: postgres
      WK_PG_PASSWORD: postgres
      WK_PG_DB: postgres
      WK_PG_MIGRATION: ./sql/migrations
      WK_JWT_SECRET: 9138e41195112b568e22480f18a42dd69b38fab5ee1a36fbf63d49b22097d22a
      WK_ROOT_PASSWORD: '123456'
    volumes:
      - ./:/app
      - go-data:/go/pkg/mod
      - go-build-data:/root/.cache/go-build
  db: 
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
  go-data:
  go-build-data:
