# This is used for local development of wavekit.
global:
  scrape_interval: 5s
  evaluation_interval: 60s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9500"]

  - job_name: standalone
    static_configs:
      - targets: ["rw:1250"]
        labels:
          risingwave_cluster: "default"
