apiVersion: v1
kind: ServiceAccount
metadata:
  name: wavekit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wavekit
subjects:
  - kind: ServiceAccount
    name: wavekit
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wavekit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wavekit
  template:
    metadata:
      labels:
        app: wavekit
    spec:
      serviceAccountName: wavekit
      containers:
        - name: dev
          image: golang:1.24-bullseye
          workingDir: /app
          volumeMounts:
            - mountPath: /app
              name: codebase
            - mountPath: /wavekit-data
              name: wavekit-pv
            - mountPath: /go/pkg/mod
              name: go-data
            - mountPath: /root/.cache/go-build
              name: go-build-data
          command:
            - go
            - run
            - cmd/wavekit/main.go
          env:
            - name: WK_PORT
              value: '30080'
            - name: WK_PG_DSN
              value: postgres://postgres:postgres@db:5432/postgres
            - name: WK_JWT_SECRET
              value: 'secret'
            - name: WK_ROOT_PASSWORD
              value: '123456'
            - name: WK_RISECTLDIR
              value: /wavekit-data/risectl
            - name: WK_METRICSPORT
              value: '9020'
            - name: WK_DEBUG_ENABLE
              value: 'true'
            - name: WK_DEBUG_PORT
              value: '8777'
            - name: HTTPS_PROXY
              value: http://172.25.128.1:10810
            - name: HTTP_PROXY
              value: http://172.25.128.1:10810
            - name: NO_PROXY
              value: localhost,127.0.0.1,10.0.0.0/8,172.25.0.0/16,192.168.0.0/16
      volumes:
        - name: codebase
          hostPath:
            path: /opt/wavekit-dev/codebase
            type: DirectoryOrCreate
        - name: wavekit-pv
          hostPath:
            path: /opt/wavekit-dev/wavekit-data
            type: DirectoryOrCreate
        - name: go-data
          hostPath:
            path: /opt/wavekit-dev/go-data
            type: DirectoryOrCreate
        - name: go-build-data
          hostPath:
            path: /opt/wavekit-dev/go-build-data
            type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
      volumes:
      - name: postgres-data
        hostPath:
          path: /opt/wavekit-dev/postgres-data
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30432
  selector:
    app: db
---
apiVersion: v1
kind: Service
metadata:
  name: wavekit
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: wavekit
---
apiVersion: v1
kind: Service
metadata:
  name: wavekit-nodeport
spec:
  type: NodePort
  ports:
    - name: wavekit
      port: 30080
      targetPort: 30080
      nodePort: 30080
    - name: wavekit-metric
      port: 9020
      targetPort: 9020
      nodePort: 30090
    - name: wavekit-debug
      port: 8777
      targetPort: 8777
      nodePort: 30087
  selector:
    app: wavekit
