// Code generated by MockGen. DO NOT EDIT.
// Source: internal/modelctx/modelctx.go
//
// Generated by this command:
//
//	mockgen -source=internal/modelctx/modelctx.go -destination=internal/modelctx/mock/modelctx_mock_gen.go -package=mock
//

// Package mock is a generated GoMock package.
package mock
