BEGIN;

CREATE TABLE IF NOT EXISTS opaque_keys (
    id              BIGSERIAL   PRIMARY KEY,
    key             BYTEA       NOT NULL,
    user_id         INT         NOT NULL REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    created_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMIT;
