// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: cluster_management_configs.sql

package querier

import (
	"context"
)

const getAutoBackupConfig = `-- name: GetAutoBackupConfig :one
SELECT cluster_id, enabled, created_at, updated_at, task_id FROM auto_backup_configs
WHERE cluster_id = $1
`

func (q *Queries) GetAutoBackupConfig(ctx context.Context, clusterID int32) (*AutoBackupConfig, error) {
	row := q.db.QueryRow(ctx, getAutoBackupConfig, clusterID)
	var i AutoBackupConfig
	err := row.Scan(
		&i.ClusterID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TaskID,
	)
	return &i, err
}

const getAutoDiagnosticsConfig = `-- name: GetAutoDiagnosticsConfig :one
SELECT cluster_id, enabled, created_at, updated_at, task_id FROM auto_diagnostics_configs
WHERE cluster_id = $1
`

func (q *Queries) GetAutoDiagnosticsConfig(ctx context.Context, clusterID int32) (*AutoDiagnosticsConfig, error) {
	row := q.db.QueryRow(ctx, getAutoDiagnosticsConfig, clusterID)
	var i AutoDiagnosticsConfig
	err := row.Scan(
		&i.ClusterID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TaskID,
	)
	return &i, err
}
