// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: metrics_stores.sql

package querier

import (
	"context"
)

const getMetricsStore = `-- name: GetMetricsStore :one
SELECT ms.id, ms.name, ms.spec, ms.created_at, ms.updated_at
FROM metrics_stores ms
    JOIN clusters c ON c.metrics_store_id = ms.id
WHERE c.id = $1
`

func (q *Queries) GetMetricsStore(ctx context.Context, id int32) (*MetricsStore, error) {
	row := q.db.QueryRow(ctx, getMetricsStore, id)
	var i MetricsStore
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Spec,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
