// Code generated by MockGen. DO NOT EDIT.
// Source: internal/task/interfaces.go
//
// Generated by this command:
//
//	mockgen -source internal/task/interfaces.go -destination internal/task/mock_gen.go -package task
//

// Package task is a generated GoMock package.
package task

import (
	reflect "reflect"

	apigen "github.com/risingwavelabs/wavekit/internal/apigen"
	modelctx "github.com/risingwavelabs/wavekit/internal/modelctx"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskStoreInterface is a mock of TaskStoreInterface interface.
type MockTaskStoreInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTaskStoreInterfaceMockRecorder
	isgomock struct{}
}

// MockTaskStoreInterfaceMockRecorder is the mock recorder for MockTaskStoreInterface.
type MockTaskStoreInterfaceMockRecorder struct {
	mock *MockTaskStoreInterface
}

// NewMockTaskStoreInterface creates a new mock instance.
func NewMockTaskStoreInterface(ctrl *gomock.Controller) *MockTaskStoreInterface {
	mock := &MockTaskStoreInterface{ctrl: ctrl}
	mock.recorder = &MockTaskStoreInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskStoreInterface) EXPECT() *MockTaskStoreInterfaceMockRecorder {
	return m.recorder
}

// CreateCronJob mocks base method.
func (m *MockTaskStoreInterface) CreateCronJob(c *modelctx.ModelCtx, timeoutDuration *string, orgID *int32, cronExpression string, specType apigen.TaskSpec) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCronJob", c, timeoutDuration, orgID, cronExpression, specType)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCronJob indicates an expected call of CreateCronJob.
func (mr *MockTaskStoreInterfaceMockRecorder) CreateCronJob(c, timeoutDuration, orgID, cronExpression, specType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCronJob", reflect.TypeOf((*MockTaskStoreInterface)(nil).CreateCronJob), c, timeoutDuration, orgID, cronExpression, specType)
}

// PauseCronJob mocks base method.
func (m *MockTaskStoreInterface) PauseCronJob(c *modelctx.ModelCtx, taskID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PauseCronJob", c, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PauseCronJob indicates an expected call of PauseCronJob.
func (mr *MockTaskStoreInterfaceMockRecorder) PauseCronJob(c, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PauseCronJob", reflect.TypeOf((*MockTaskStoreInterface)(nil).PauseCronJob), c, taskID)
}

// PushTask mocks base method.
func (m *MockTaskStoreInterface) PushTask(c *modelctx.ModelCtx, spec apigen.TaskSpec, opts ...TaskOpt) (int32, error) {
	m.ctrl.T.Helper()
	varargs := []any{c, spec}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PushTask", varargs...)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PushTask indicates an expected call of PushTask.
func (mr *MockTaskStoreInterfaceMockRecorder) PushTask(c, spec any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{c, spec}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushTask", reflect.TypeOf((*MockTaskStoreInterface)(nil).PushTask), varargs...)
}

// ResumeCronJob mocks base method.
func (m *MockTaskStoreInterface) ResumeCronJob(c *modelctx.ModelCtx, taskID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResumeCronJob", c, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResumeCronJob indicates an expected call of ResumeCronJob.
func (mr *MockTaskStoreInterfaceMockRecorder) ResumeCronJob(c, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeCronJob", reflect.TypeOf((*MockTaskStoreInterface)(nil).ResumeCronJob), c, taskID)
}

// UpdateCronJob mocks base method.
func (m *MockTaskStoreInterface) UpdateCronJob(c *modelctx.ModelCtx, taskID int32, timeoutDuration *string, orgID *int32, cronExpression string, specType apigen.TaskSpec) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCronJob", c, taskID, timeoutDuration, orgID, cronExpression, specType)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCronJob indicates an expected call of UpdateCronJob.
func (mr *MockTaskStoreInterfaceMockRecorder) UpdateCronJob(c, taskID, timeoutDuration, orgID, cronExpression, specType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCronJob", reflect.TypeOf((*MockTaskStoreInterface)(nil).UpdateCronJob), c, taskID, timeoutDuration, orgID, cronExpression, specType)
}
