// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/risingwavelabs/wavekit/internal/apps/server"
	"github.com/risingwavelabs/wavekit/internal/config"
	"github.com/risingwavelabs/wavekit/internal/controller"
	"github.com/risingwavelabs/wavekit/internal/middleware"
	"github.com/risingwavelabs/wavekit/internal/model"
	"github.com/risingwavelabs/wavekit/internal/service"
)

// Injectors from wire.go:

func InitializeServer() (*server.Server, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	modelInterface, err := model.NewModel(configConfig)
	if err != nil {
		return nil, err
	}
	authServiceInterface, err := service.NewAuthService(configConfig)
	if err != nil {
		return nil, err
	}
	serviceInterface := service.NewService(configConfig, modelInterface, authServiceInterface)
	middlewareMiddleware := middleware.NewMiddleware(authServiceInterface)
	controllerController := controller.NewController(serviceInterface, middlewareMiddleware)
	initService := service.NewInitService(modelInterface, serviceInterface)
	serverServer, err := server.NewServer(configConfig, controllerController, middlewareMiddleware, initService)
	if err != nil {
		return nil, err
	}
	return serverServer, nil
}
