// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/cloudcarver/anchor/wire"
	"github.com/risingwavelabs/wavekit/internal/config"
	"github.com/risingwavelabs/wavekit/internal/conn/http"
	"github.com/risingwavelabs/wavekit/internal/conn/meta"
	"github.com/risingwavelabs/wavekit/internal/conn/metricsstore"
	"github.com/risingwavelabs/wavekit/internal/conn/sql"
	"github.com/risingwavelabs/wavekit/internal/controller"
	"github.com/risingwavelabs/wavekit/internal/service"
	"github.com/risingwavelabs/wavekit/internal/task"
	"github.com/risingwavelabs/wavekit/internal/zcore/initapp"
	"github.com/risingwavelabs/wavekit/internal/zcore/injection"
	"github.com/risingwavelabs/wavekit/internal/zcore/model"
	"github.com/risingwavelabs/wavekit/internal/zgen/taskgen"
)

// Injectors from wire.go:

func InitializeApplication() (*initapp.App, error) {
	application, err := wire.InitializeApplication()
	if err != nil {
		return nil, err
	}
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	modelInterface, err := model.NewModel(configConfig)
	if err != nil {
		return nil, err
	}
	authInterface := injection.InjectAuth(application)
	sqlConnectionManegerInterface := sql.NewSQLConnectionManager(modelInterface)
	risectlManagerInterface, err := meta.NewRisectlManager(configConfig)
	if err != nil {
		return nil, err
	}
	metricsManager, err := metricsstore.NewMetricsManager(modelInterface, configConfig)
	if err != nil {
		return nil, err
	}
	metaHttpManagerInterface := http.NewMetaHttpManager()
	taskStoreInterface := injection.InjectTaskStore(application)
	taskRunner := taskgen.NewTaskRunner(taskStoreInterface)
	serviceInterface, err := service.NewService(configConfig, modelInterface, authInterface, sqlConnectionManegerInterface, risectlManagerInterface, metricsManager, metaHttpManagerInterface, taskRunner, taskStoreInterface)
	if err != nil {
		return nil, err
	}
	initService := service.NewInitService(modelInterface, serviceInterface)
	serverInterface, err := controller.NewSeverInterface(configConfig, serviceInterface, authInterface, initService)
	if err != nil {
		return nil, err
	}
	validator := controller.NewValidator(modelInterface, authInterface)
	executorInterface := task.NewTaskExecutor(taskRunner, modelInterface, risectlManagerInterface, metaHttpManagerInterface)
	taskHandler := taskgen.NewTaskHandler(executorInterface)
	app := initapp.NewApp(application, serverInterface, validator, taskHandler)
	return app, nil
}
